services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:5000

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - database
    environment:
      - DATABASE_URL=mongodb://database:27017/wetransfer_clone
      - JWT_SECRET=your_secret_key
      - STORAGE_PATH=/app/uploads

  database:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

  file-storage:
    build: 
      context: ./file-storage
      dockerfile: Dockerfile
    volumes:
      - uploads:/app/uploads
    ports:
      - "9000:9000"

volumes:
  mongodb_data:
  uploads:
