services:
  frontend:
    image: tiritibambix/itransfer-frontend
    ports:
      - "3500:80"
    environment:
      # L'utilisateur peut définir ici l'URL du backend
      - REACT_APP_BACKEND_URL=http://machineIP:5000
    volumes:
      - ./iTransfer/frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
    image: tiritibambix/itransfer-backend
    ports:
      - "4500:5000"
    environment:
      # L'utilisateur peut définir ici l'URL du frontend
      - FRONTEND_URL=http://machineIP:3500
      - DATABASE_URL=mysql://mariadb_user:mariadb_pass@db/mariadb_db
      - SECRET_KEY=super_secret_key
    volumes:
      - ./iTransfer/backend_data:/app/data
      - ./iTransfer/uploads:/app/uploads
    depends_on:
      - db

  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mariadb_db
      MYSQL_USER: mariadb_user
      MYSQL_PASSWORD: mariadb_pass
    ports:
      - "3306:3306"
    volumes:
      - ./iTransfer/db_data:/var/lib/mysql

volumes:
  db_data:
  backend_data:
  uploads:
