# Configuration pour iTransfer
# Pour un usage local : pas besoin de modifier les valeurs par défaut
# Pour un usage avec reverse proxy : définir FRONTEND_URL et BACKEND_URL avec les URLs publiques

services:
  frontend:
    image: tiritibambix/itransfer-frontend
    ports:
      - "3500:80"
    environment:
      # URL publique du backend (avec https:// si derrière reverse proxy)
      # Exemple local : http://localhost:5500
      # Exemple proxy : https://api.itransfer.domain.com
      - BACKEND_URL=${BACKEND_URL:-http://localhost:5500}
    depends_on:
      - backend
    networks:
      - itransfer-network

  backend:
    image: tiritibambix/itransfer-backend
    ports:
      - "5500:5000"
    environment:
      # URL publique du frontend (avec https:// si derrière reverse proxy)
      # Exemple local : http://localhost:3500
      # Exemple proxy : https://itransfer.domain.com
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:3500}
      # Identifiants administrateur
      - ADMIN_USERNAME=${ADMIN_USERNAME:-adminuser}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-adminuserpassword}
      # Configuration base de données
      - DATABASE_URL=mysql+mysqldb://mariadb_user:mariadb_pass@db/mariadb_db
      # Configuration HTTPS
      - FORCE_HTTPS=true
      - PROXY_COUNT=1
    volumes:
      - ./backend/data:/app/data
      - ./backend/uploads:/app/uploads
    depends_on:
      db:
        condition: service_healthy
    networks:
      - itransfer-network

  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mariadb_db
      MYSQL_USER: mariadb_user
      MYSQL_PASSWORD: mariadb_pass
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u root --password=$MYSQL_ROOT_PASSWORD || echo 'Healthcheck failed' >> /var/log/healthcheck.log"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      - itransfer-network

networks:
  itransfer-network:
    driver: bridge