services:
  itransfer-backend:
    image: tiritibambix/itransfer-backend:latest
    container_name: itransfer-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend/uploads:/app/uploads
    environment:
      SMTP_SERVER: smtp.example.com
      SMTP_PORT: 587
      SMTP_EMAIL: your_email@example.com
      SMTP_PASSWORD: your_password
    depends_on:
      - itransfer-db

  itransfer-frontend:
    image: tiritibambix/itransfer-frontend:latest
    container_name: itransfer-frontend
    ports:
      - "3000:3000"

  itransfer-db:
    image: postgres:13
    container_name: itransfer-db
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: uploads_db
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
