services:
  frontend:
    image: tiritibambix/itransfer-frontend
    environment:
      - BACKEND_URL=https://api.itransfer.domain.com  # Production API URL
    ports:
      - "3500:80"                                    # Can be changed to any port
    depends_on:
      - backend
    networks:
      - itransfer-network

  backend:
    image: tiritibambix/itransfer-backend
    ports:
      - "5500:5000"                                  # Can be changed to any port
    environment:
      - FRONTEND_URL=https://itransfer.domain.com    # Production frontend URL
      - ADMIN_USERNAME=adminuser
      - ADMIN_PASSWORD=adminuserpassword
      - DATABASE_URL=mysql+mysqldb://itransfer:itransfer@db/itransfer
    volumes:
      - ./backend/data:/app/data
      - ./uploads:/app/uploads
    depends_on:
      db:
        condition: service_healthy
    networks:
      - itransfer-network

  db:
    image: mariadb:10.6
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=itransfer
      - MYSQL_USER=itransfer
      - MYSQL_PASSWORD=itransfer
    volumes:
      - ./db_data:/var/lib/mysql
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u root --password=$MYSQL_ROOT_PASSWORD || echo 'Healthcheck failed' >> /var/log/healthcheck.log"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      - itransfer-network

networks:
  itransfer-network:
    driver: bridge