services:
  frontend:
    image: tiritibambix/itransfer-frontend
    ports:
      - "3500:80"
    volumes:
      - ./iTransfer/frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - itransfer-network

  backend:
    image: tiritibambix/itransfer-backend
    ports:
      - "5500:5000"
    environment:
      - FRONTEND_URL=http://localhost:3500
      - ADMIN_USERNAME=adminuser
      - ADMIN_PASSWORD=adminuserpassword
      - DATABASE_URL=mysql://mariadb_user:mariadb_pass@db/mariadb_db
    volumes:
      - ./iTransfer/backend/data:/app/data
      - ./iTransfer/uploads:/app/uploads
    depends_on:
      db:
        condition: service_healthy
    networks:
      - itransfer-network
    restart: unless-stopped

  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mariadb_db
      MYSQL_USER: mariadb_user
      MYSQL_PASSWORD: mariadb_pass
    ports:
      - "3306:3306"
    volumes:
      - ./iTransfer/db_data:/var/lib/mysql
      - ./iTransfer/backend/init/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot_password"]
      interval: 10s
      timeout: 20s
      retries: 10
      start_period: 60s
    networks:
      - itransfer-network
    restart: unless-stopped

volumes:
  db_data:

networks:
  itransfer-network:
    driver: bridge