version: '3'

services:
  backend:
    image: tiritibambix/itransfer-backend  # Utilisation de l'image pré-construite
    ports:
      - "5000:5000"
    volumes:
      - ./backend/data:/data          # Volume pour stocker les données de l'application
      - ./backend/uploads:/uploads     # Volume pour les fichiers uploadés

  frontend:
    image: tiritibambix/itransfer-frontend  # Utilisation de l'image pré-construite
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend/data:/data           # (Facultatif) Volume pour stocker des données du frontend
