name: Build and Push Multi-Arch Docker Images

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'LICENSE'
      - 'README.md'
      - 'TODO.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'LICENSE'
      - 'README.md'
      - 'TODO.md'
  workflow_dispatch:

jobs:
  build-push:
    runs-on: ubuntu-24.04

    steps:
    # Step 1: Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # Step 3: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 4: Check dependencies with pip-check
    - name: Check dependencies with pip-check
      run: |
        docker run --rm -v $(pwd):/app -w /app python:3.10-slim sh -c " \
        python -m venv venv && \
        . venv/bin/activate && \
        pip install pip-check && \
        pip-check"

    # Step 5: Build and Push Backend Image (Multi-Arch)
    - name: Build and Push Backend
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./backend/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          tiritibambix/itransfer-backend:latest
          tiritibambix/itransfer-backend:${{ github.sha }}
        cache-from: type=registry,ref=tiritibambix/itransfer-backend:buildcache
        cache-to: type=registry,ref=tiritibambix/itransfer-backend:buildcache,mode=max

    # Step 6: Build and Push Frontend Image (Multi-Arch)
    - name: Build and Push Frontend
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./frontend/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          tiritibambix/itransfer-frontend:latest
          tiritibambix/itransfer-frontend:${{ github.sha }}
        cache-from: type=registry,ref=tiritibambix/itransfer-frontend:buildcache
        cache-to: type=registry,ref=tiritibambix/itransfer-frontend:buildcache,mode=max
