name: Build and Push Docker Images

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'LICENSE'
      - 'README.md'
      - 'TODO.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'LICENSE'
      - 'README.md'
      - 'TODO.md'
  workflow_dispatch:

jobs:
  build-push:
    runs-on: ubuntu-24.04

    steps:
    # Étape 1 : Cloner le dépôt
    - name: Checkout repository
      uses: actions/checkout@v4

    # Étape 2 : Configurer Docker Buildx pour le multi-arch
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        install: true
        use: true

    # Étape 3 : Connexion à Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Étape 4 : Vérifier les dépendances avec pip-check
    - name: Check dependencies with pip-check
      run: |
        docker run --rm -v $(pwd):/app -w /app python:3.10-slim sh -c " \
        python -m venv venv && \
        . venv/bin/activate && \
        pip install pip-check && \
        pip-check"

    # Étape 5 : Construire et pousser l'image Docker pour le backend
    - name: Build and Push Backend (Multi-Arch)
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./backend/Dockerfile
        push: true
        platforms: linux/amd64,linux/arm64
        tags: |
          tiritibambix/itransfer-backend:latest
        cache-from: type=registry,ref=tiritibambix/itransfer-backend:buildcache
        cache-to: type=registry,ref=tiritibambix/itransfer-backend:buildcache,mode=max
        provenance: false

    # Étape 6 : Construire et pousser l'image Docker pour le frontend
    - name: Build and Push Frontend (Multi-Arch)
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./frontend/Dockerfile
        push: true
        platforms: linux/amd64,linux/arm64
        tags: |
          tiritibambix/itransfer-frontend:latest
        cache-from: type=registry,ref=tiritibambix/itransfer-frontend:buildcache
        cache-to: type=registry,ref=tiritibambix/itransfer-frontend:buildcache,mode=max
        provenance: false
